### PR TITLE
some copy / paste typos

### PR DESCRIPTION
**Pull request by dickhardt**

### CODE REVIEW

**Comment by dickhardt** [comment]
looks like BatchGetItem result processing was forgotten

**Comment by dickhardt** [comment]
When do you expect to look at this pull request? The BatchGetItem patch is pretty critical! :)

**Comment by ryanfitz** [comment]
Thanks for the pull request, the doc changes looks good.

For the changes to updateItem, BatchGetItem, and Type.updateAttributes could you update/add some tests for these changes. All the tests are written in mocha and can be run by running 'make test' and live under test/unit dir. I can also work on this tomorrow when I have some time.

This also reminds me that I should create a ticket for me to create a section to the readme about contributions.

**Comment by ryanfitz** [comment]
I just merged in these changes to master. I did slightly change around the meta object returned from batch get item.

meta =  { 
  ConsumedCapacityUnits: { 
    Table1: 1,
    Table2: 4
  }
}

Thanks again for the updates

**Comment by dickhardt** [comment]
Cool. Will check out the tests. Have not used Mocha before.

**Pull request closed without merging**
